######################################################
#                  Awards Collections                #
######################################################

templates:
  awards:
    smart_label:
      sort_by: release.desc
      all:
        label: <<smart_label>>
    sort_title: ++++<<collection_name>>

#  cannes:
 #   use_palm: true
  #  name_palm: "Cannes Palme d'Or Winners"
   # use_year_collections: false
    #smart_label:
     # sort_by: 
      #  - release.desc
#      all:
 #       label: <<smart_label>>
  #  sort_title: ++++<<collection_name>>
   # summary: Collection of Cannes Golden Palm Award Winners.

    
collections:
  Oscars:
    template: {name: awards}
    url_poster: https://raw.githubusercontent.com/puddpuller/Kometa-Configs/main/configs/assets/awards/Oscars.png
    trakt_list:
      - https://trakt.tv/users/pandali/lists/oscar-nomination-1975-2023
      - https://trakt.tv/users/dlcrain58/lists/2024-oscar-nominated-movies
      - https://trakt.tv/users/dlcrain58/lists/2025-oscar-nominated-movies
      - https://trakt.tv/users/dlcrain58/lists/2026-oscar-nominated-movies
    summary: Every movie to receive an Oscar nomination from 1931-Present.

#  "Cannes Palme d'Or Winners":
 #   template: {name: cannes}
    #radarr_add_missing: true
