######################################################
#                Seasonal Collections                #
######################################################

templates:
  seasonal:
    label: season_<<season>>
    url_poster: https://raw.githubusercontent.com/puddpuller/Kometa-Configs/main/configs/assets/seasonal/<<season>>.png
    schedule: <<schedule>>
    visible_library: true
    visible_home: true
    visible_shared: true
    sort_title: ++++++<<collection_name>>
    collection_order: random

######################################################
#                   COLLECTIONS                      #
######################################################

collections:

  Santa’s Nice List:
    template:
      name: seasonal
      season: christmas
      schedule: range(11/01-12/31)
    trakt_list:
      - https://trakt.tv/users/k0meta/lists/christmas-extravaganza-non-tv-movie
      - https://trakt.tv/users/ubjeckle/lists/christmas-movies
      - https://trakt.tv/users/littlestella3/lists/christmas
      - https://trakt.tv/users/triadcool/lists/christmas
      - https://trakt.tv/users/pterisaur/lists/christmas
      - https://trakt.tv/users/oldmankestis/lists/christmas
      - https://trakt.tv/users/biggsandroid/lists/christmas
    summary: >
      A festive collection celebrating the spirit, traditions, and magic of the holiday season —
      from timeless classics to modern favorites.

  Spooktober:
    template:
      name: seasonal
      season: halloween
      schedule: range(09/15-10/31)
    trakt_list:
      - https://trakt.tv/users/oldmankestis/lists/horror
      - https://trakt.tv/users/movistapp/lists/horror
      - https://trakt.tv/users/g0g0/lists/horror
      - https://trakt.tv/users/pterisaur/lists/halloween
      - https://trakt.tv/users/k0meta/lists/spooktober-copy
    plex_search:
      any:
        genre: Horror
    summary: >
      Films celebrating Halloween, spooky folklore, and horror traditions —
      ranging from lighthearted scares to atmospheric chills.

  Cupid’s Favorites:
    template:
      name: seasonal
      season: valentine
      schedule: range(02/01-02/14)
    trakt_list:
      - https://trakt.tv/users/martincz29/lists/valentine
      - https://trakt.tv/users/planetjimbo/lists/valentine-s-day-collection
      - https://trakt.tv/users/triadcool/lists/valentine
      - https://trakt.tv/users/oya-kesh/lists/seasonal-valentine
      - https://trakt.tv/users/dweagle79/lists/valentine-s-day
    summary: >
      Celebrate love in all its forms with romantic films and heartfelt stories
      about connection, passion, and meaningful relationships.

  Roots & Rise – Black History Stories:
    template:
      name: seasonal
      season: black-history
      schedule: range(02/01-02/29)
    trakt_list:
      - https://trakt.tv/users/madmapper/lists/black-history
      - https://trakt.tv/users/jenninja/lists/black-history-docs
      - https://trakt.tv/users/bluephi8/lists/black-history
      - https://trakt.tv/users/chadee93/lists/black-shows-movies-black-leads
    summary: >
      Celebrates the achievements, stories, and cultural contributions of Black individuals
      throughout history, honoring the past, present, and future.

  Bunnies & Blessings:
    template:
      name: seasonal
      season: easter
      schedule: range(03/20-04/30)
    trakt_list:
      - https://trakt.tv/users/axee4/lists/easter
      - https://trakt.tv/users/neyoke/lists/easter
      - https://trakt.tv/users/blakemp/lists/easter
      - https://trakt.tv/users/trovolar/lists/easter
      - https://trakt.tv/users/blazin887/lists/easter
      - https://trakt.tv/users/dvitale71/lists/easter
    summary: >
      Celebrate the joy and renewal of Easter with a blend of fun, family-friendly rabbit
      adventures and inspiring stories of faith, hope, and new beginnings.

  Shamrock Stories:
    template:
      name: seasonal
      season: patrick
      schedule: range(03/01-03/17)
    trakt_list:
      - https://trakt.tv/users/planetjimbo/lists/st-patrick-s-day-collection
      - https://trakt.tv/users/madmapper/lists/st-patrick-s-day
      - https://trakt.tv/users/blazin887/lists/st-patricks-day
    summary: >
      Celebrate St. Patrick’s Day with films and stories filled with charm, folklore,
      mischief, and a touch of festive magic.

  Legends of the Lunar New Year:
    template:
      name: seasonal
      season: lunar
      schedule: range(01/21-02/20)
    trakt_list:
      - https://trakt.tv/users/sandstorms/lists/horse-movies-shows
    summary: >
     Celebrate the Lunar New Year with a vibrant mix of films and shorts inspired by tradition, folklore, and cultural storytelling. Alongside themes of renewal, luck, and togetherness, this collection embraces the spirit and symbolism of the year’s zodiac sign, weaving its traits and energy into stories that honor heritage while welcoming new beginnings.

  Voices of Asia and the Pacific:
    template:
      name: seasonal
      season: asia-pacific
      schedule: range(05/01-05/31)
    trakt_list:
      - https://trakt.tv/users/k0meta/lists/asian-american-pacific-islander-heritage-month
      - https://trakt.tv/users/explicitlyemily/lists/aapi-festival
      - https://trakt.tv/users/asnguy01/lists/chinese-movies
      - https://trakt.tv/users/mgperdices/lists/korean-movies
      - https://trakt.tv/users/xanatos-david/lists/japanese-movies
      - https://trakt.tv/users/komobu/lists/korean-movies
    summary: >
     Celebrate the histories, cultures, and creative voices of Asian and Pacific Islander communities through a diverse selection of films and shorts. Spanning generations and genres, these stories highlight tradition, resilience, and contemporary life, honoring the lasting impact and rich contributions of Asian and Pacific Islander heritage.
     
  Her Story on Screen:
    template:
      name: seasonal
      season: women
      schedule: range(03/01-03/31)
    trakt_list:
      - https://trakt.tv/users/pterisaur/lists/women-s-history-month
      - https://trakt.tv/users/ymendel/lists/women-s-history-month
      - https://trakt.tv/users/trovolar/lists/women-s-history-month
    summary: >
     Celebrate the achievements, resilience, and influence of women through a powerful selection of films and shorts. Spanning history, genres, and generations, these stories highlight leadership, creativity, and courage, honoring the women who have shaped the world and continue to inspire change.
     
  Culturas en Movimiento:
    template:
      name: seasonal
      season: hispanic
      schedule: range(09/15-10/15)
    trakt_list:
      - https://trakt.tv/users/drachenplatinum/lists/national-hispanic-heritage-movies
      - https://trakt.tv/users/k0meta/lists/hispanic-heritage-month
      - https://trakt.tv/users/drachenplatinum/lists/national-hispanic-heritage-movies
    summary: >
     Celebrate the richness, diversity, and creativity of Hispanic and Latino cultures through a vibrant selection of films and shorts. Highlighting tradition, family, music, and contemporary stories, these films honor the contributions, heritage, and voices that continue to shape communities and inspire future generations.

   Honoring Indigenous Voices:
    template:
      name: seasonal
      season: native
      schedule: range(11/01-11/30)
    trakt_list:
      - https://trakt.tv/users/trovolar/lists/native-american-heritage-month
    summary: >
     Celebrate the history, culture, and resilience of Native American communities through a diverse selection of films and shorts. Highlighting tradition, storytelling, and contemporary life, these stories honor the enduring contributions, heritage, and voices of Indigenous peoples across generations.
     
  Pride in Motion:
    template:
      name: seasonal
      season: pride
      schedule: range(06/01-06/30)
    trakt_list:
      - https://trakt.tv/users/luna_t3ch/lists/pride-month-waving_white_flag-rainbow
      - https://trakt.tv/users/smatthew/lists/lgbt
    summary: >
     Celebrate the diversity, resilience, and creativity of LGBTQ+ communities through a vibrant selection of films and shorts. Highlighting stories of identity, love, activism, and personal triumph, these films honor the voices, experiences, and contributions that have shaped Pride and continue to inspire visibility and acceptance.
     
