######################################################
#                  IMDb Collection                   #
######################################################

templates:
  imdb:
    imdb_chart: <<chart>>_<<library_type>>s
    smart_label:
      sort_by: audience_rating.desc
      all:
        label: <<smart_label>>
    sort_title: +++++<<collection_name>>
    summary: The top 250 best <<library_type>>s of all time based on IMDb user ratings.

collections:
  IMDb Top 250:
    template: {name: imdb, chart: top}
    url_poster: https://raw.githubusercontent.com/puddpuller/Kometa-Configs/main/configs/assets/charts/imdb.png
